name: Pipeline

on:
  push:
    branches: 
      - deploy

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
         
      - name: setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: test
          
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
         
      - name: Build
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: shadowJar
      - name: Upload built Jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: applicationJar
          path: build/libs/esop-0.1-all.jar

  terraform:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config='access_key=${{ secrets.AWS_ACCESS_KEY_ID }}' -backend-config='secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}'

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
         
      - name: Download built Jar artifact
        uses: actions/download-artifact@v3
        with:
          name: applicationJar
         
      - name: Copy built Jar to remote machine instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "esop-0.1-all.jar,start.sh"
          target: "/app/"
       
      - name: startup the application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /bin/bash /app/start.sh
       
         
        
